### ISSUE TITLE
Editor crashes and won't sync up. May be related to invalid cursor position.

### ISSUE THREAD

**Issue by thesunny** [wleroux/slate-collaborative#1] opened 2020-06-21 06:41 UTC
Hi @wleroux,

If I rapidly make changes across editors, the editor will crash. I don't have concrete steps, I'm just hitting keys quickly in each editor.

Here is the error mesage:

![image](https://user-images.githubusercontent.com/469587/85218447-3dde7980-b34f-11ea-8f76-061b9f5f226b.png)

Here is a screen shot.

![image](https://user-images.githubusercontent.com/469587/85218469-767e5300-b34f-11ea-9cda-a5ed3368590c.png)

**Comment by wleroux** [comment] 2020-06-22 03:39
Hey @thesunny , this issue should be resolved. There were a few things that could be causing this: removing a node that is an ancestor of a merge node... splitting a node in between the two nodes that are being merged.

After resolving these cases, I could not reproduce it anymore.

**Closed** 2020-07-01 03:03 UTC
Labels: bug
